# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- mdhb

pool:
  vmImage: ubuntu-latest

stages:
    
 - stage: BuildGradle
   displayName: Build the Gradle project Hl7-fhir-converter IntegrationWorks fork
   jobs:
   - job: Build_JAR
     displayName: Build JAR to be deployed to Azure Artifact Feed
     steps:
         
     - task: DownloadSecureFile@1
       name: mvnSettings
       displayName: 'Download Maven settings'
       inputs:
         secureFile: 'settings.xml'

     - task: MavenAuthenticate@0
       displayName: Maven Authenticate Artifacts
       inputs:
         artifactsFeeds: 'LinuxForHealthHL7Converter'

     - task: Gradle@2
       displayName: 'Gradle build and publish to artifact feed'
       inputs:
         workingDirectory: ''
         gradleWrapperFile: 'gradlew'
         gradleOptions: '-Xmx3072m'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.11'
         jdkArchitectureOption: 'x64'
         publishJUnitResults: true
         testResultsFiles: '**/TEST-*.xml'
         options: '-x test -Pversion=1.0.21-SNAPSHOT -PmvnUserSettingsFile=$(mvnSettings.secureFilePath)'
         tasks: 'publish'


